<Delivery>
    BoxLayout:
        orientation: "vertical"
        size: root.width*0.7, root.height*0.7
        pos: root.width/7, root.width/9
        spacing: 10
        GridLayout:
            cols: 2
            spacing: 10
            Label:
                text: "order"
                font_size: 36
            TextInput:
                font_size:36
            Label:
                text: "dress"
                font_size: 36
            TextInput:
                font_size:36
            Label:
                text: "Phone"
                font_size: 36
            TextInput:
                font_size:36
            Button:
                text: "Accept"
                background_color: 0, 0.7, 0.1
                font_size: 36
                size_hint: 0.5, 0.5
                pos_hint: {"x":0.275}






